package org.fortandroid.greendao_android.generated_models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import org.fortandroid.greendao_android.generated_models.Contact;
import org.fortandroid.greendao_android.generated_models.Address;

import org.fortandroid.greendao_android.generated_models.ContactDao;
import org.fortandroid.greendao_android.generated_models.AddressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig addressDaoConfig;

    private final ContactDao contactDao;
    private final AddressDao addressDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(Address.class, addressDao);
    }
    
    public void clear() {
        contactDaoConfig.getIdentityScope().clear();
        addressDaoConfig.getIdentityScope().clear();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

}
